services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    platform: linux/amd64

  app:
    build: .
    container_name: nestjs_app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: mongodb://admin:admin@mongodb:27017/mongodb
    networks:
      - my_network

networks:
  my_network:
    driver: bridge